version: '3.8'

services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    restart: always
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./backend/_data/qdrant:/qdrant/storage
      # Uncomment if you want a custom config file:
      # - ./backend/_data/qdrant_config/production.yaml:/qdrant/config/production.yaml
    networks:
      - internal_net

  embedding:
    container_name: embedding
    build:
      context: ./backend
      dockerfile: embedding/Dockerfile
      args:
        - EMBEDDING_MODEL_PATH=${EMBEDDING_MODEL_PATH}
        - EMBEDDING_MODEL_REVISION=${EMBEDDING_MODEL_REVISION}
        - EMBEDDING_MODEL_DTYPE=${EMBEDDING_MODEL_DTYPE}
        - EMBEDDING_MODEL_TOKENIZER_PATH=${EMBEDDING_MODEL_TOKENIZER_PATH}
        - EMBEDDING_MODEL_TOKENIZER_REVISION=${EMBEDDING_MODEL_TOKENIZER_REVISION}
        - EMBEDDING_MODEL_ASPECTS="${EMBEDDING_MODEL_ASPECTS}"
    expose:
      - 50051
    read_only: true
    networks:
      - internal_net
    environment:
      - EMBEDDING_MODEL_MODEL_PATH=${EMBEDDING_MODEL_PATH}
      - EMBEDDING_MODEL_MODEL_REVISION=${EMBEDDING_MODEL_REVISION}
      - EMBEDDING_MODEL_DIM=${EMBEDDING_MODEL_DIM}
      - EMBEDDING_MODEL_MAX_INPUT_LENGTH=${EMBEDDING_MODEL_MAX_INPUT_LENGTH}
      - EMBEDDING_MODEL_ASPECTS="${EMBEDDING_MODEL_ASPECTS}"

  logic:
    container_name: logic
    build:
      context: ./backend
      dockerfile: logic/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend/_data/backend:/data
    read_only: true
    networks:
      - internal_net
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      - DATABASE_VOLUME=/data
      - EMBEDDING_SERVICE_HOST=${EMBEDDING_SERVICE_HOST}
      - EMBEDDING_SERVICE_PORT=${EMBEDDING_SERVICE_PORT}
      - VECTORSTORE_SERVICE_HOST=${VECTORSTORE_SERVICE_HOST}
      - VECTORSTORE_SERVICE_PORT=${VECTORSTORE_SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DEBUG=${DEBUG}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    expose:
      - 8501
    read_only: true
    networks:
      - public_net
      - internal_net
    user: appuser
    volumes:
      - /home/appuser/.streamlit
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      - BACKEND_API_URL=${BACKEND_API_URL}

networks:
  internal_net:
    external: true
  public_net:
    external: true

