version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/_data/postgres-init:/docker-entrypoint-initdb.d
      - ${POSTGRES_BACKUPS}:/backups
    expose:
      - 5432
    networks:
      - internal_net

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1-unprivileged
    restart: always
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./backend/_data/qdrant:/qdrant/storage
      # Uncomment if you want a custom config file:
      # - ./backend/_data/qdrant_config/production.yaml:/qdrant/config/production.yaml
    networks:
      - internal_net

  embedding:
    container_name: embedding
    build:
      context: ./backend
      dockerfile: embedding/Dockerfile
      args:
        - EMBEDDING_MODEL_PATH=${EMBEDDING_MODEL_PATH}
        - EMBEDDING_MODEL_REVISION=${EMBEDDING_MODEL_REVISION}
        - EMBEDDING_MODEL_DTYPE=${EMBEDDING_MODEL_DTYPE}
        - EMBEDDING_MODEL_TOKENIZER_PATH=${EMBEDDING_MODEL_TOKENIZER_PATH}
        - EMBEDDING_MODEL_TOKENIZER_REVISION=${EMBEDDING_MODEL_TOKENIZER_REVISION}
        - EMBEDDING_MODEL_ASPECTS=${EMBEDDING_MODEL_ASPECTS}
    expose:
      - 50051
    read_only: true
    networks:
      - internal_net
    environment:
      - EMBEDDING_MODEL_MODEL_PATH=${EMBEDDING_MODEL_PATH}
      - EMBEDDING_MODEL_MODEL_REVISION=${EMBEDDING_MODEL_REVISION}
      - EMBEDDING_MODEL_DIM=${EMBEDDING_MODEL_DIM}
      - EMBEDDING_MODEL_MAX_INPUT_LENGTH=${EMBEDDING_MODEL_MAX_INPUT_LENGTH}
      - EMBEDDING_MODEL_ASPECTS=${EMBEDDING_MODEL_ASPECTS}

  logic:
    container_name: logic
    build:
      context: ./backend
      dockerfile: logic/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend/_data/backend:/data
    read_only: true
    networks:
      - internal_net
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      - DATABASE_VOLUME=/data
      - EMBEDDING_SERVICE_HOST=${EMBEDDING_SERVICE_HOST}
      - EMBEDDING_SERVICE_PORT=${EMBEDDING_SERVICE_PORT}
      - VECTORSTORE_SERVICE_HOST=${VECTORSTORE_SERVICE_HOST}
      - VECTORSTORE_SERVICE_PORT=${VECTORSTORE_SERVICE_PORT}
      - VECTORSTORE_COLLECTION_NAME=${VECTORSTORE_COLLECTION_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWKS_URL=http://frontend:3000/api/auth/jwks
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_RESOURCES=${POSTGRES_DB_RESOURCES}
      - POSTGRES_DB_USERS=${POSTGRES_DB_USERS}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DEBUG=${DEBUG}

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - STAGE=production
      - BACKEND_API_URL=${BACKEND_API_URL}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/medidex?schema=public
    networks:
      - internal_net
      - public_net

networks:
  internal_net:
    external: true
  public_net:
    external: true

volumes:
  postgres_data: