---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	prepare_report_pdf(prepare_report_pdf)
	load_next_initial(load_next_initial)
	classify_initial(classify_initial)
	select_very_likely(select_very_likely)
	compare_very_likely(compare_very_likely)
	prepare_likely_review(prepare_likely_review)
	load_next_likely(load_next_likely)
	classify_likely_review(classify_likely_review)
	prepare_unsure_review(prepare_unsure_review)
	load_next_unsure(load_next_unsure)
	classify_unsure(classify_unsure)
	match_not_found_end(match_not_found_end)
	summarize_evaluation(summarize_evaluation)
	suggest_new_study(suggest_new_study)
	__end__([<p>__end__</p>]):::last
	__start__ --> prepare_report_pdf;
	classify_initial --> load_next_initial;
	classify_likely_review --> load_next_likely;
	classify_unsure --> load_next_unsure;
	compare_very_likely -. &nbsp;no_match_after_compare&nbsp; .-> prepare_likely_review;
	compare_very_likely -. &nbsp;match_found&nbsp; .-> summarize_evaluation;
	load_next_initial -. &nbsp;has_study&nbsp; .-> classify_initial;
	load_next_initial -. &nbsp;no_more_initial&nbsp; .-> select_very_likely;
	load_next_likely -. &nbsp;has_likely&nbsp; .-> classify_likely_review;
	load_next_likely -. &nbsp;no_more_likely&nbsp; .-> prepare_unsure_review;
	load_next_likely -. &nbsp;match_found&nbsp; .-> summarize_evaluation;
	load_next_unsure -. &nbsp;has_unsure&nbsp; .-> classify_unsure;
	load_next_unsure -. &nbsp;match_not_found&nbsp; .-> match_not_found_end;
	load_next_unsure -. &nbsp;match_found&nbsp; .-> summarize_evaluation;
	match_not_found_end --> summarize_evaluation;
	prepare_likely_review --> load_next_likely;
	prepare_report_pdf --> load_next_initial;
	prepare_unsure_review --> load_next_unsure;
	select_very_likely -. &nbsp;has_very_likely&nbsp; .-> compare_very_likely;
	select_very_likely -. &nbsp;no_very_likely&nbsp; .-> prepare_likely_review;
	summarize_evaluation -. &nbsp;done&nbsp; .-> __end__;
	summarize_evaluation -. &nbsp;needs_new_study&nbsp; .-> suggest_new_study;
	suggest_new_study --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
