from __future__ import annotations

from .schemas import ReportDto, StudyDto

MOCK_REPORT = ReportDto(
    reportId=1001,
    title="Vitamin D and bone density in older adults",
    authors=["A. Smith","B. Lee"],
    year=2022,
    abstract="We evaluate bone density outcomes after vitamin D supplementation in older adults.",
    trialId="NCT01234567",
)

MOCK_STUDIES = [
    StudyDto(
        status="Completed",
        numberParticipants="180",
        countries=["US"],
        duration="9 months",
        studyId=2003,
        createdAt="2022-06-20",
        comparison="Vitamin D plus calcium vs placebo",
        shortName="Vitamin D and calcium in older adults",
        updatedAt="2022-08-01",
        trialId="NCT09876543",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="150",
        countries=["UK"],
        duration="6 months",
        studyId=2002,
        createdAt="2021-09-10",
        comparison="High fiber vs standard diet",
        shortName="Dietary fiber and microbiome",
        updatedAt="2021-11-02",
        trialId="NCT07654321",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="200",
        countries=["US","Canada"],
        duration="12 months",
        studyId=2001,
        createdAt="2022-12-01",
        comparison="Vitamin D vs placebo",
        shortName="Vitamin D bone density trial",
        updatedAt="2023-01-15",
        trialId="NCT01234567",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="220",
        countries=["Canada"],
        duration="10 months",
        studyId=2004,
        createdAt="2021-03-12",
        comparison="Resistance training vs usual care",
        shortName="Resistance training for fall prevention",
        updatedAt="2021-04-20",
        trialId="NCT05554444",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="90",
        countries=["US"],
        duration="4 months",
        studyId=2005,
        createdAt="2020-05-12",
        comparison="Omega-3 supplement vs placebo",
        shortName="Omega-3 and cognitive outcomes",
        updatedAt="2020-06-15",
        trialId="NCT01112223",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="110",
        countries=["Germany"],
        duration="8 months",
        studyId=2006,
        createdAt="2021-01-08",
        comparison="Vitamin B12 vs placebo",
        shortName="Vitamin B12 and anemia in older adults",
        updatedAt="2021-02-20",
        trialId="NCT03334445",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="140",
        countries=["UK"],
        duration="12 months",
        studyId=2007,
        createdAt="2022-04-18",
        comparison="Calcium plus exercise vs exercise alone",
        shortName="Exercise and calcium for bone density",
        updatedAt="2022-06-01",
        trialId="NCT05556667",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="175",
        countries=["US"],
        duration="12 months",
        studyId=2008,
        createdAt="2022-09-25",
        comparison="Vitamin D supplementation vs placebo",
        shortName="Vitamin D supplementation in older adults",
        updatedAt="2022-10-30",
        trialId="NCT07778889",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="190",
        countries=["US"," Canada"],
        duration="10 months",
        studyId=2009,
        createdAt="2022-11-05",
        comparison="Vitamin D plus calcium vs placebo",
        shortName="Vitamin D plus calcium for bone density",
        updatedAt="2022-12-20",
        trialId="NCT09990001",
    ),
    StudyDto(
        status="Completed",
        numberParticipants="210",
        countries=["US"," Canada"],
        duration="12 months",
        studyId=2010,
        createdAt="2023-01-02",
        comparison="Vitamin D vs placebo",
        shortName="Vitamin D and bone density in older adults (replication)",
        updatedAt="2023-02-01",
        trialId="NCT01234568",
    ),
]
