syntax = "proto3";

package embed;

service EmbedService {
  rpc GetEmbeddingAspects (stream EmbedRequest) returns (stream EmbedResponseAspects);
  rpc GetEmbedding (stream EmbedRequest) returns (stream EmbedResponse);
}

message EmbedRequest {
  string id = 1;
  repeated string text = 2;
}

message EmbeddingVector {
  repeated float values = 1;
}

message AspectVectors {
  repeated EmbeddingVector aspect_embeddings = 1;
}

message EmbedResponse {
  string id = 1;
  repeated EmbeddingVector embedding = 2; 
}

message EmbedResponseAspects {
  string id = 1;
  repeated EmbeddingVector embedding = 2;
  repeated AspectVectors aspect_embeddings = 3;
}