syntax = "proto3";

package embed;

service EmbedService {
  rpc GetEmbeddingAspects (stream EmbedRequest) returns (stream EmbedResponseAspects);
  rpc GetEmbedding (stream EmbedRequest) returns (stream EmbedResponse);
}

message EmbedRequest {
  string text = 1;
}

message EmbeddingVector {
  repeated float values = 1;
}

message EmbedResponse {
  EmbeddingVector embedding = 1; 
}

message EmbedResponseAspects {
  EmbeddingVector embedding = 1;
  repeated EmbeddingVector aspect_embeddings = 2;
}