name: Build and Deploy Docker

on:
  push:
    branches: [ "prod" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout prod branch
      uses: actions/checkout@v3
      with:
        ref: prod  # Checkout the prod branch directly
    - name: Deploy application
      run: |
        cd ~/meerkat-tool
        sudo docker compose up -d --build